//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Семестровая
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class AgeInGroups
    {
        public int UsId { get; set; }
        public string FName { get; set; }
        public string Lname { get; set; }
        public Nullable<System.DateTime> BDay { get; set; }
    }
}
