//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Семестровая
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Photos
    {
        public int PhotoID { get; set; }
        public int AlbumID { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
    
        public virtual Albums Albums { get; set; }
    }
}
