//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Семестровая
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Walls
    {
        public int GroupID { get; set; }
        public int WallID { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public System.DateTime datePost { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
